micronaut:
  application:
    name: zeebe-workers
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 10

kafka:
  bootstrap:
    servers: localhost:9092

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
